name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Docker login
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        echo "Iniciando el login"
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
        echo "Finalizando el login"
        
    - name: Docker build
      run: |
        docker build -t yaiirdev/github-actions-graphql:0.0.2 .

    - name: Docker push
      run: |
        docker push yaiirdev/github-actions-graphql:0.0.2
